version: master-{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
clone_folder: c:\projects\scap-workbench
install:
- cmd: vcpkg install curl libxml2 libxslt bzip2 pcre pthreads qt5:x64-windows
cache: c:\tools\vcpkg\installed\
before_build:
- cmd: >-
    cd build

    cmake -DENABLE_PYTHON3=FALSE -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
build:
  project: c:\projects\scap-workbench\build\scap-workbench.sln
  verbosity: minimal
